/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#ifndef APPLICATION_H
#define APPLICATION_H

#include <BCDS_Retcode.h>
#include "applicationTypes.h"


Retcode_T initGlobalVariables_application();

#endif
