/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#include <math.h>
#include <BCDS_Environmental.h>
#include <XdkSensorHandle.h>
#include <BCDS_Magnetometer.h>
#include <bma2x2.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdbool.h>
#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <stdint.h>
#include "Noise_sensor.h"
#include "SensorEnvironment.h"
#include "SensorMagnetometer.h"
#include "SensorAccelerometer.h"
#include "InputOutputSDCardSd.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

uint32_t SYSTEM_TIME = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEveryXDK110Startup1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	char result2010825919_buf[175] = {0};
	char *result2010825919 = result2010825919_buf;
	
	char mainHandleEveryXDK110Startup11Result2010825919_2_buf[175] = {0};
	snprintf(mainHandleEveryXDK110Startup11Result2010825919_2_buf, sizeof(mainHandleEveryXDK110Startup11Result2010825919_2_buf), "System time,Acceleration magnitude,Acceleration x,Acceleration y,Acceleration z,Magnetometer magnitude,Magnetometer x,Magnetometer y,Magnetometer z,Temperature,Noise,Humidity");
	memcpy(result2010825919, mainHandleEveryXDK110Startup11Result2010825919_2_buf, sizeof(mainHandleEveryXDK110Startup11Result2010825919_2_buf));
	
	char* _newInputOutputSDCardSd_Writer_1 = result2010825919;
	exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_1);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}

Retcode_T HandleEvery10Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	SYSTEM_TIME++;


	return NO_EXCEPTION;
}

Retcode_T HandleEvery1Minute1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	struct bma2x2_accel_data sensorAccelerometerModalityPreparation_1;
	exception = SensorAccelerometer_ReadXYZ(&sensorAccelerometerModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	Magnetometer_XyzData_T sensorMagnetometerModalityPreparation_2;
	exception = Magnetometer_readXyzLsbData(XdkMagnetometer_BMM150_Handle, &sensorMagnetometerModalityPreparation_2);
	if(exception != NO_EXCEPTION) return exception;
	
	Environmental_Data_T sensorEnvironmentModalityPreparation_3;
	exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_3);
	if(exception != NO_EXCEPTION) return exception;
	
	float noise_sensorModalityPreparation_4;
	exception = readNoiseSensor(&noise_sensorModalityPreparation_4);
	if(exception != NO_EXCEPTION) return exception;
	
	char result617471011_buf[140] = {0};
	char *result617471011 = result617471011_buf;
	
	char mainHandleEvery1Minute12Result617471011_2_buf[140] = {0};
	snprintf(mainHandleEvery1Minute12Result617471011_2_buf, sizeof(mainHandleEvery1Minute12Result617471011_2_buf), "\n%" PRIu32 ",%" PRIu32 ",%" PRId32 ",%" PRId32 ",%" PRId32 ",%" PRIu16 ",%" PRId32 ",%" PRId32 ",%" PRId32 ",%" PRId32 ",%.6g,%" PRIu32 "", SYSTEM_TIME, (uint32_t)sqrt((sensorAccelerometerModalityPreparation_1.x * sensorAccelerometerModalityPreparation_1.x) + (sensorAccelerometerModalityPreparation_1.y * sensorAccelerometerModalityPreparation_1.y) + (sensorAccelerometerModalityPreparation_1.z * sensorAccelerometerModalityPreparation_1.z)), sensorAccelerometerModalityPreparation_1.x, sensorAccelerometerModalityPreparation_1.y, sensorAccelerometerModalityPreparation_1.z, sensorMagnetometerModalityPreparation_2.resistance, sensorMagnetometerModalityPreparation_2.xAxisData, sensorMagnetometerModalityPreparation_2.yAxisData, sensorMagnetometerModalityPreparation_2.zAxisData, sensorEnvironmentModalityPreparation_3.temperature, noise_sensorModalityPreparation_4
	, sensorEnvironmentModalityPreparation_3.humidity);
	memcpy(result617471011, mainHandleEvery1Minute12Result617471011_2_buf, sizeof(mainHandleEvery1Minute12Result617471011_2_buf));
	
	char* _newInputOutputSDCardSd_Writer_1 = result617471011;
	exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_1);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}


