/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#ifndef INPUTOUTPUTSDCARD_SDCARD_H
#define INPUTOUTPUTSDCARD_SDCARD_H

#include <BCDS_Retcode.h>


/**
 * Sets up the SDCard.
 */
Retcode_T InputOutputSDCardSd_Setup(void);

/**
 * Enables the SDCard sensor.
 */
Retcode_T InputOutputSDCardSd_Enable(void);

/**
 * Provides read access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Read(char** result);

/**
 * Provides write access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Write(char** result);


#endif
