/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#include <XDK_NoiseSensor.h>
#include <BCDS_Retcode.h>
#include "MitaExceptions.h"

#define NOISE_SENSOR_READ_TIMEOUT 100

Retcode_T Noise_sensor_Setup(void)
{
	return NoiseSensor_Setup(2560);
	
	return NO_EXCEPTION;
}

Retcode_T Noise_sensor_Enable(void)
{
	return NoiseSensor_Enable();
	
	return NO_EXCEPTION;
}

Retcode_T readNoiseSensor(float *result) {
	NoiseSensor_ReadRmsValue(result, NOISE_SENSOR_READ_TIMEOUT);
}

