/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#ifndef NOISE_SENSOR_NOISE_SENSOR_H
#define NOISE_SENSOR_NOISE_SENSOR_H

#include <BCDS_Retcode.h>


/**
 * Sets up the noise_sensor.
 */
Retcode_T Noise_sensor_Setup(void);

/**
 * Enables the noise_sensor sensor.
 */
Retcode_T Noise_sensor_Enable(void);


Retcode_T readNoiseSensor(float *result);

#endif
