/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2023-03-14 13:15:33
 */


#ifndef SENSORMAGNETOMETER_MAGNETOMETER_H
#define SENSORMAGNETOMETER_MAGNETOMETER_H

#include <BCDS_Retcode.h>


/**
 * Sets up the magnetometer.
 */
Retcode_T SensorMagnetometer_Setup(void);

/**
 * Enables the magnetometer sensor.
 */
Retcode_T SensorMagnetometer_Enable(void);



#endif
